### ISSUE TITLE
How to link your huggingface account to the program

### ISSUE THREAD

**Issue by lesquoyb** [ACROSS-Lab/GAMA-Code-Generator#2]
I followed the readme to install the environment on my computer and tried to run the inference script, but I get the error message: `Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json.
Access to model mistralai/Mistral-7B-Instruct-v0.2 is restricted. You must be authenticated to access it.`.
How do I link my huggingface account to access it ?

**Comment by norwayiscoming** [comment]
This error is because in `command-line-inference.py` I'm loading PEFT model on Mistral as a based model.

**Comment by norwayiscoming** [comment]
I've updated the README file with 3 options:

1. **Use PEFT model via HuggingFace** (which is what I'm doing in the `command-line-inference.py`): 
- You'll need a HuggingFace account and you should log in before running the inference using `huggingface-cli login` with your token. You can find more details [here](https://huggingface.co/docs/huggingface_hub/guides/cli).
- After creating your HuggingFace account, please visit this [link](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2) to get access to Mistral. They will require you to agree something to get access to their model. (Not a big deal)

2. **Use GAMA-Code-Generator** 
- I have updated this new option so we won't need to permit permission from Mistral since we won't load the Mistral as our based model anymore. Instead, we will load my fine-tuned model.

3. **Download the Code-Generator model straight to your local machine**: 
- It will take a long time since the model is huge.
